[package]
name = "bus"
version = "1.4.1"

description = "A lock-free, bounded, single-producer, multi-consumer, broadcast channel."
readme = "README.md"

authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

documentation = "https://docs.rs/bus"
homepage = "https://github.com/jonhoo/bus"
repository = "https://github.com/jonhoo/bus.git"

keywords = ["channel","broadcast","lock-free"]
categories = ["asynchronous", "concurrency"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/bus" }

[features]
async = ["futures", "void"]
bench = []

[dependencies]
atomic-option = "0.1"
futures = { optional = true, version = "0.1.14" }
num_cpus = "1.6.2"
parking_lot_core = "0.2.2"
void = { optional = true, version = "1.0.2" }

[dev-dependencies]
tokio = "0.1.7"

[profile.release]
debug = true

[[bin]]
name = "bench"
path = "src/bench.rs"
